### ISSUE TITLE
when i run the  generate_dot_json_file function in build_java_graph.py raise the follw error, the acr31/features-javac is already installed

### ISSUE THREAD

**Issue by KellyZhang2020** [shangqing-liu/GraphSearchNet#5]

**Comment by KellyZhang2020** [comment]
```
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -j
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at uk.ac.cam.acr31.features.javac.dot.GraphToDot.main(GraphToDot.java:38)
```

**Comment by shangqing-liu** [comment]
You can refer to our paper for the released java graph construction tool
