### ISSUE TITLE
when i run the generate_dot_json_file function in build_java_graph.py raise the follw error, the acr31/features-javac is already installed 

### ISSUE THREAD

**Issue by KellyZhang2020** [shangqing-liu/GraphSearchNet#6]
When i run the `generate_dot_json_file()` function in `build_java_graph.py`, raise the follow error:
```
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -j
        at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
        at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
        at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
        at uk.ac.cam.acr31.features.javac.dot.GraphToDot.main(GraphToDot.java:38)
```

And in the https://github.com/acr31/features-javac/blob/511d1baead2be2513baa818fdba1d9effa547c52/dot/src/main/java/uk/ac/cam/acr31/features/javac/dot/GraphToDot.java there are three options, as follow, but don't have the option `-j`
```
option.addOption("i", "input-file", true, "Input filename");
option.addOption("o", "output-file", true, "Output filename");
option.addOption("v", "verbose-dot", false, "Verbose dot output");
```

**Comment by frederik-markus** [comment]
Hi Kelly, no the Java Graph builder never worked for me either. I'm sorry I cannot be of more help.
